require_relative '../models/customer'
require_relative '../models/film'
require_relative '../models/ticket'

require( 'pry-byebug')

customer1 = Customer.new({'name' => 'David', 'cash' => 10})
customer1.save()
customer2 = Customer.new({'name' => 'Fee', 'cash' => 20})
customer2.save()
customer3 = Customer.new({'name' => 'Tigger', 'cash' => 30})
customer3.save()
customer4 = Customer.new({'name' => 'Topsy', 'cash' => 50})
customer4.save()
customer5 = Customer.new({'name' => 'Ralf', 'cash' => 15})
customer5.save()


film1 = Film.new({'title' => 'Guardians of the Galaxy 2', 'price' => 5})
film1.save()
film2 = Film.new({'title' => 'Doctor Strange 3D', 'price' => 10})
film2.save()
film3 = Film.new({'title' => 'Back To The Future Trilogy', 'price' => 15})
film3.save()
film4 = Film.new({'title' => 'Yellow Submarine', 'price' => 5})
film4.save()
film5 = Film.new({'title' => 'M*A*S*H', 'price' => 5})
film5.save


ticket1 = Ticket.new({'film_id' => film1.id, 'customer_id' => customer1.id})
ticket1.save()
ticket2 = Ticket.new({'film_id' => film3.id, 'customer_id' => customer2.id})
ticket2.save()
ticket3 = Ticket.new({'film_id' => film4.id, 'customer_id' => customer3.id})
ticket3.save()
ticket4 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer4.id})
ticket4.save()
ticket5 = Ticket.new({'film_id' => film5.id, 'customer_id' => customer5.id})
ticket5.save()
ticket6 = Ticket.new({'film_id' => film1.id, 'customer_id' => customer1.id})
ticket6.save()
ticket7 = Ticket.new({'film_id' => film5.id, 'customer_id' => customer2.id})
ticket7.save()
ticket8 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer3.id})
ticket8.save()
ticket9 = Ticket.new({'film_id' => film4.id, 'customer_id' => customer4.id})
ticket9.save()
ticket10 = Ticket.new({'film_id' => film5.id, 'customer_id' => customer5.id})
ticket10.save()
ticket11 = Ticket.new({'film_id' => film3.id, 'customer_id' => customer1.id})
ticket11.save()
ticket12 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer2.id})
ticket12.save()
ticket13 = Ticket.new({'film_id' => film4.id, 'customer_id' => customer3.id})
ticket13.save()
ticket14 = Ticket.new({'film_id' => film1.id, 'customer_id' => customer4.id})
ticket14.save()
ticket15 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer5.id})
ticket15.save()
ticket16 = Ticket.new({'film_id' => film4.id, 'customer_id' => customer1.id})
ticket16.save()
ticket17 = Ticket.new({'film_id' => film5.id, 'customer_id' => customer2.id})
ticket17.save()
ticket18 = Ticket.new({'film_id' => film3.id, 'customer_id' => customer3.id})
ticket18.save()
ticket19 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer4.id})
ticket19.save()
ticket20 = Ticket.new({'film_id' => film2.id, 'customer_id' => customer5.id})
ticket20.save()

binding.pry
nil
